config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'

  get '/startworker', to: 'landing#startworker'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  resources :denizens
  resources :landing
  resources :elements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/denizen.rb
class Denizen < ApplicationRecord

  def is_home?
    if self.location == "home"
      return true
    else
      return false
    end
  end

  def set_location(location)
    self.location = location
    if location == "home"
      give_access
    end
  end

  def give_access
    return unlock_doors if access_level == 2
    if self.access_level == 1
      Denizen.all.each do |e|
        if e.access_level > 1
          return unlock_doors if e.location == "home"
        end
      end
    end
  end

  private
  def access_level
    return 2 if self.access == "admin"
    return 1 if self.access == "guest"
    return 0
  end

  def unlock_doors
    url_builder = "#{Rails.application.secrets.homeassistant[:url]}:#{Rails.application.secrets.homeassistant[:port]}/api/services/lock/unlock"

    uri = URI.parse(url_builder)
    http = Net::HTTP.new(uri.host, uri.port)
    http['x-ha-access'] = Rails.application.secrets.homeassistant[:password] unless Rails.application.secrets.homeassistant[:password].blank?
    header = {'Content-Type': 'text/json'}
    request = Net::HTTP::Post.new(uri.request_uri, header)
    # request.body = user.to_json
    # Send the request
    response = http.request(request)
  end
end

app/controllers/denizens_controller.rb
class DenizensController < ApplicationController
  before_action :set_denizen, only: [:show, :edit, :update, :destroy]

  # GET /denizens
  # GET /denizens.json
  def index
    @denizens = Denizen.all
  end

  # GET /denizens/1
  # GET /denizens/1.json
  def show
  end

  # GET /denizens/new
  def new
    @denizen = Denizen.new
  end

  # GET /denizens/1/edit
  def edit
  end

  # POST /denizens
  # POST /denizens.json
  def create
    @denizen = Denizen.new(denizen_params)

    respond_to do |format|
      if @denizen.save
        format.html { redirect_to @denizen, notice: 'Denizen was successfully created.' }
        format.json { render :show, status: :created, location: @denizen }
      else
        format.html { render :new }
        format.json { render json: @denizen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /denizens/1
  # PATCH/PUT /denizens/1.json
  def update
    respond_to do |format|
      if @denizen.update(denizen_params)
        format.html { redirect_to @denizen, notice: 'Denizen was successfully updated.' }
        format.json { render :show, status: :ok, location: @denizen }
      else
        format.html { render :edit }
        format.json { render json: @denizen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /denizens/1
  # DELETE /denizens/1.json
  def destroy
    @denizen.destroy
    respond_to do |format|
      format.html { redirect_to denizens_url, notice: 'Denizen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_denizen
      @denizen = Denizen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def denizen_params
      params.require(:denizen).permit(:full_name, :nickname, :access)
    end
end

app/helpers/denizens_helper.rb
module DenizensHelper
end

app/views/denizens/_form.html.erb
<%= form_with(model: denizen, local: true) do |form| %>
  <% if denizen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(denizen.errors.count, "error") %> prohibited this denizen from being saved:</h2>

      <ul>
      <% denizen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name, id: :denizen_full_name %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :denizen_nickname %>
  </div>

  <div class="field">
    <%= form.label :access %>
    <%= form.text_field :access, id: :denizen_access %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/denizens/edit.html.erb
<h1>Editing Denizen</h1>

<%= render 'form', denizen: @denizen %>

<%= link_to 'Show', @denizen %> |
<%= link_to 'Back', denizens_path %>

app/views/denizens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Denizens</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Nickname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @denizens.each do |denizen| %>
      <tr>
        <td><%= denizen.full_name %></td>
        <td><%= denizen.nickname %></td>
        <td><%= link_to 'Show', denizen %></td>
        <td><%= link_to 'Edit', edit_denizen_path(denizen) %></td>
        <td><%= link_to 'Destroy', denizen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Denizen', new_denizen_path %>

<%= link_to 'Test worker', '/startworker' %>

               

app/views/denizens/new.html.erb
<h1>New Denizen</h1>

<%= render 'form', denizen: @denizen %>

<%= link_to 'Back', denizens_path %>

app/views/denizens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @denizen.full_name %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @denizen.nickname %>
</p>

<p>
  <strong>Access Level:</strong>
  <%= @denizen.access %>
</p>

<%= link_to 'Edit', edit_denizen_path(@denizen) %> |
<%= link_to 'Back', denizens_path %>