config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'

  get '/startworker', to: 'landing#startworker'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  resources :denizens
  resources :landing
  resources :elements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/element.rb
class Element < ApplicationRecord

  def get_history(timestamp: nil)
    # NOTE (Michael): Exmaple date format "2016-02-06T22:15:00+00:00", if not passed in, only returns the day before
    get_homeassistant_creds
    url_builder = "#{@homeassistant_info[:url]}:#{@homeassistant_info[:port]}/api/history/period"
    url_builder += "/#{timestamp}" unless timestamp.blank?
    url_builder += "?filter_entity_id=#{self.entity_id}"

    return api_call_get(url_builder)
  end

  def test_me
    puts "Hello world"
    return "Hello world"
  end

  def set_type
    raiser "You must override this method in each model inheriting from Product!" if self.type.blank?
  end

  def get_state
    get_homeassistant_creds
    url_builder = "#{@homeassistant_info[:url]}:#{@homeassistant_info[:port]}/api/states/#{self.entity_id}"

    return JSON.parse(api_call_get(url_builder))
  end

  def get_simple_state
    state_hash = get_state
    return state_hash["state"]
  end

  def set_state(state, extra_states:nil)
    # NOTE (Michael): Extra states come in as string and gets tacked on at the end
    url_builder = "#{@homeassistant_info[:url]}:#{@homeassistant_info[:port]}/api/states/#{self.entity_id}"
    body_builder = '{ "state":'+"#{state}"
    body_builder += extra_states unless extra_states.blank?
    body_builder += "}"
  end

  def get_homeassistant_creds
    @homeassistant_info = { url: Rails.application.secrets.homeassistant[:url],
                            port: Rails.application.secrets.homeassistant[:port],
                            password: Rails.application.secrets.homeassistant[:password]}
  end

  def api_call_get(url)
    uri = URI.parse(url)

    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)
    request.initialize_http_header({"x-ha-access" => @homeassistant_info[:password]}) unless @homeassistant_info[:password].blank?
    return http.request(request).read_body
  end

  def api_call_post(url, requestbody)
    uri = URI.parse(url)

    http = Net::HTTP.new(uri.host, uri.port)
    if @homeassistant_info[:password].blank?
      request = Net::HTTP::Post.new(uri.request_uri)
    else
      #request["x-ha-access"] = @homeassistant_info[:password]}) unless @homeassistant_info[:password].blank?
      request = Net::HTTP::Post.new(uri.request_uri, initheader: {'x-ha-access' => @homeassistant_info[:password]})
    end

    request.body = requestbody
    return http.request(request).read_body
  end
end

app/models/elements/automation.rb
class Automation < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "Automation"
  end
end

app/models/elements/binary_sensor.rb
class BinarySensor < Element
  def self.model_name
    Element.model_name
  end
  def set_type
    self.type = "BinarySensor"
  end
end

app/models/elements/climate.rb
class Climate < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "Climate"
  end

 def set_temperature(temperature)
   get_homeassistant_creds
   body_builder ='{"entity_id": "'+ "#{self.entity_id}" +'",  "temperature": "'+ "#{temperature}" +'" }'
   url = "#{@homeassistant_info[:url]}:#{@homeassistant_info[:port]}/api/services/climate/set_temperature"
   api_call_post url, body_builder
 end
end

app/models/elements/configurator.rb
class Configurator < Element
  def self.model_name
    Element.model_name
  end
  def set_type
    self.type = "Configurator"
  end
end

app/models/elements/device_tracker.rb
class DeviceTracker < Element

  def self.model_name
    Element.model_name
  end

  def owner_name
    unless self.denizen_id.blank?
      return Denizen.find(self.denizen_id).full_name
    else
      return nil
    end
  end

  def set_location(location)
    set_owner_location(location)
    self.location = location
    self.save
  end

  def set_type
    self.type = "DeviceTracker"
  end

  private
  def set_owner_location(location)
    unless self.denizen_id.blank?
      owner = Denizen.find(self.denizen_id)
      owner.set_location(location)
      if owner.save
        return true
      else
        return false
      end
    else
      return nil
    end
  end
end

app/models/elements/group.rb
class Group < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "Group"
  end
end

app/models/elements/light.rb
class Light < Element
  def self.model_name
    Element.model_name
  end

  def turn_on(color_name:"white", brightness_pct: "100")
    get_homeassistant_creds
    body_builder ='{"entity_id": "'+ self.entity_id+'", "color_name": "'+color_name+'", "brightness_pct": "'+brightness_pct+'"}'
    url = "#{@homeassistant_info[:url]}:#{@homeassistant_info[:port]}/api/services/light/turn_on"
    api_call_post url, body_builder
  end

  def turn_off
    get_homeassistant_creds
    body_builder ='{"entity_id": "'+ self.entity_id+'"}'
    url = "#{@homeassistant_info[:url]}:#{@homeassistant_info[:port]}/api/services/light/turn_off"
    api_call_post url, body_builder
  end
end

app/models/elements/lock.rb
class Lock < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "Lock"
  end

  def unlock
    get_homeassistant_creds
    body_builder ='{"entity_id": "lock.front_door"}'
    url = "#{@homeassistant_info[:url]}:#{@homeassistant_info[:port]}/api/services/lock/unlock"
    api_call_post url, body_builder
  end

  def lock
    get_homeassistant_creds
    body_builder ='{"entity_id": "'+ self.entity_id+'"}'
    url = "#{@homeassistant_info[:url]}:#{@homeassistant_info[:port]}/api/services/lock/lock"
    api_call_post url, body_builder
  end
end

app/models/elements/media_player.rb
class MediaPlayer < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "MediaPlayer"
  end
end

app/models/elements/scene.rb
class Scene < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "Scene"
  end
end

app/models/elements/sensor.rb
class Sensor < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "Sensor"
  end
end

app/models/elements/smart_configurator.rb
class SmartConfigurator < Element
  def self.model_name
    Element.model_name
  end
  def set_type
    self.type = "Configurator"
  end
end

app/models/elements/smart_updater.rb
# class Updater < Element
#   def self.model_name
#     Element.model_name
#   end
#
#   def set_type
#     self.type = "Zone"
#   end
# end

app/models/elements/sun.rb
class Sun < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "Sun"
  end
end

app/models/elements/switch.rb
class Switch < Element
  def self.model_name
    Element.model_name
  end

  def set_type
    self.type = "Switch"
  end
end

app/models/elements/zone.rb
class Zone < Element
  def self.model_name
    Element.model_name
  end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Element was successfully created.' }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to elements_url, notice: 'Element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:entity_id, :friendly_name, :location, :denizen_id, :state)
    end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_form.html.erb
<%= form_with(model: element, local: true) do |form| %>
  <% if element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :entity_id %>
    <%= form.text_field :entity_id, id: :element_entity_id %>
  </div>

  <div class="field">
    <%= form.label :friendly_name %>
    <%= form.text_field :friendly_name, id: :element_friendly_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :element_location %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :element_state %>
  </div>

  <div class="field">
    <%= form.label :denizen_id %>
    <%= form.text_field :denizen_id, id: :element_denizen_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elements</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= element.entity_id %></td>
        <td><%= element.friendly_name %></td>
        <td><%= element.state %></td>
        <td><%= link_to 'Show', element %></td>
        <td><%= link_to 'Edit', edit_element_path(element) %></td>
        <td><%= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Element', new_element_path %>

app/views/elements/new.html.erb
<h1>New Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @element.friendly_name %>
</p>

<p>
  <strong>Entity id:</strong>
  <%= @element.entity_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @element.location %>
</p>

<p>
  <strong>State:</strong>
  <%= @element.state %>
</p>

<p>
  <strong>Denizen id:</strong>
  <%= @element.denizen_id %>
</p>

<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>